{
 "title": "API Dashboard",
 "time": { "from": "2024-11-24T10:35:57.631Z", "to": "2024-11-24T22:35:57.631Z" },
 "panels": [
  {
   "title": "HTTP average duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_milliseconds_sum[5m]) / rate(http_requests_total[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Calculator Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(errors_calculator_total{job=\"api\"}[5m])"
    }
   ]
  },
  {
   "title": "HTTP requests per route",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"api\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Last Values",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_sum1n{job=\"api\", instance=\"api:8080\"}",
     "legendFormat": "Sum1n"
    },
    {
     "expr": "last_fibo{job=\"api\", instance=\"api:8080\"}",
     "legendFormat": "Fibo"
    },
    {
     "expr": "list_size{job=\"api\", instance=\"api:8080\"}",
     "legendFormat": "List size"
    },
    {
     "expr": "last_calculator{job=\"api\", instance=\"api:8080\"}",
     "legendFormat": "Calculator"
    }
   ]
  }
 ]
}